workflows:
  android-debug-build:
    name: Build Android APK
    environment:
      java: 17
    scripts:
      - name: Generate Gradle Wrapper
        script: gradle wrapper
      - name: Build APK Debug
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
